apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
spec:
  selector: 
    app: {{ .Release.Name }}-service
  type: NodePort  
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000