## Nginx Ingress
## Follow https://devopscube.com/setup-ingress-kubernetes-nginx-controller/

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nginx-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  # Use the host you used in your kubernetes Ingress Configurations
  - host: icg.monitoring.com
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 30300
        path: /prometheus
        pathType: Prefix
        
